#!/usr/bin/env bash
# Handles various signals
echo $$ > /tmp/myscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /tmp/myscript.pid; exit 0' SIGTERM
trap 'rm -f /tmp/myscript.pid; exit 0' SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
